config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get '/intro' => 'redirection#intro'
  get '/how_to' => 'redirection#instructions'
  
  get '/create/group' => 'home#create_group'
  post '/create/group' => 'home#create_group_exec'
  get '/create/place' => 'home#create_place'
  post '/create/place' => 'home#create_place_exec'
  
  get '/find/group' => 'home#group'
  
  get '/find/place' => 'home#place'
  
  post '/find/place/like' => 'home#likes'
  
  post '/find/place/search' => 'home#place_search'
  post '/find/group/search' => 'home#group_search'
  
  get '/find/group/detail/:group_id' => 'home#group_detail'
  get '/find/place/detail/:place_id' => 'home#place_detail'
  
  get '/find/group/apply/:group_id' => 'home#group_apply'
  post '/find/place/apply/before' => 'home#place_apply_before'
  post '/find/place/apply/before/cautions' => 'home#place_apply_before_confirm'
  post '/find/place/apply' => 'home#place_apply'
  post '/find/group/apply/:place_id' => 'home#group_apply_exec'
  post '/find/place/apply/:place_id' => 'home#place_apply_exec'
  post '/find/group/destroy/:group_id' => 'home#group_destroy_exec'
  post '/find/place/destroy/:place_id' => 'home#place_destroy_exec'
  
  get '/find/group/edit/:group_id' => 'home#group_edit'
  get '/find/place/edit/:place_id' => 'home#place_edit'
  post '/find/place/edit/:place_id' => 'home#place_edit_exec'
  post '/find/group/edit/:group_id' => 'home#group_edit_exec'
  
  delete '/find/group/cancel/:group_id' => 'home#group_cancel'
  delete '/find/place/cancel/:place_id' => 'home#place_cancel'
  
  post '/find/group/member_out' => 'home#member_out'
  
  get '/mypage/reservations/:resv_id' => 'home#reservations'
  post '/mypage/reservations/cancel' => 'home#reservations_cancel'
  post '/mypage/reservations/confirm' => 'home#reservations_confirm'
  
  post '/find/place/reservation/search' => 'home#resv_search'
  
  
  get '/login' => 'redirection#login_user_type'
  post '/login' => 'redirection#login_user_type'
  
  get '/mypage'=>'home#mypage'
  
  get '/mypage/timetable' => 'home#timetable'
  get '/mypage/timetable/edit' => 'home#timetable_edit'
  post '/mypage/timetable/edit' => 'home#timetable_edit_exec'
  
  devise_for :users, controllers: { sessions: 'users/sessions' , registrations: 'users/registrations' }
  devise_for :owners, controllers: { sessions: 'users/sessions' }
  

end

app/controllers/redirection_controller.rb
class RedirectionController < ApplicationController
  def login_user_type
    if user_signed_in? or owner_signed_in? then
      flash[:already] = "이미 로그인하셨습니다."
      redirect_to root_path
    end
  end
end

app/helpers/redirection_helper.rb
module RedirectionHelper
end

app/views/redirection/instructions.html.erb
<%= render 'home/navbar' %>
<main>
    <div class="container">
        <article>
            <h3>팀플의 세계를 <i>효과적으로</i> 활용하는 방법</h3>
            <hr>
            <div class="row">
                <div class="six columns">
                    <h5>내가 팀플의 리더라면</h5>
                    <%= link_to "그룹 생성하기", "/create/group", class:"btn btn-xs btn-embossed btn-info" %>를 통해 팀플을 관리할 수 있는 페이지를 생성하고, 팀원들 간 시간표를 대조하여 프로젝트를 하기 좋은 최적의 시간을 찾아보세요. 프로젝트를 해야 할 장소가 필요할 경우에는, <%= link_to "장소 찾기", "/find/place", class:"btn btn-xs btn-embossed btn-warning" %>를 통해 프로젝트 장소를 예약 후 확보할 수 있어요. 
                </div>
                <div class="six columns">
                    <h5>내가 팀플의 팀원이라면</h5>
                    <%= link_to "그룹 찾기", "/find/group", class:"btn btn-xs btn-embossed btn-info" %>를 통해 나의 팀플 페이지를 찾아보세요. 가입하신 후에는 팀원들 간의 시간표 대조를 통해 프로젝트를 할 수 있는 최적의 시간을 찾을 수 있습니다.
                </div>
            </div>
            <hr>
            <div class="row">
                <h5>대관 관계자분들은</h5>
                 <%= link_to "장소 생성하기", "/create/place", class:"btn btn-xs btn-embossed btn-info" %>를 통해 대관을 허가하시려는 장소에 대한 정보를 등록하여주세요. 프로젝트 장소가 필요한 대학생들이 직접 예약, 방문할 것입니다.
            </div>
        </article>
        <hr>
        <div class="tip" align='center'>[서비스 이용 전 유의사항] 시간표 등록이 반드시 필요합니다.<br>등록하지 않은 사용자께서는 시간표 등록을 하신 후에 서비스 이용이 가능합니다.</div>
    </div>
</main>

app/views/redirection/intro.html.erb
<%= render 'home/navbar' %>
<main class="intro valign-wrapper" align="center">
        <div class="tile">
            <h1 style="color:#104972;">이것은... 팀플의 세계</h1>
            <hr>
            <quote style="color:#104972;">팀프로젝트를 좀 더 마음 편하게 할 수는 없을까?</quote>
            <p style="color:#104972;"><i>팀플의 세계</i>는 팀프로젝트를 좀 더 편리하게 진행할 수 있게끔<br>팀 전용 페이지 생성하고 관리할 수 있는 기능을 제공할 뿐만 아니라,<br>팀원 간 프로젝트 수행 가능 시간을 추천해드리고,<br>필요한 경우 대관 관련 기관과의 연계로 팀프로젝트를 수행할 수 있는,<br>장소를 예약하실 수 있는 서비스를 제공해드립니다.</p>
            <hr>
            <% if user_signed_in? then %>
                <%= link_to "팀프로젝트 그룹 생성", "/create/group", {method: :get, class:"btn btn-block btn-lg btn-success"} %><br>
            <% else %>
                <%= link_to "장소 등록", "/create/place", {method: :get, class:"btn btn-block btn-lg btn-success"} %><br>
            <% end %>
            <%= link_to "서비스 이용 방법", "/how_to", class:"btn btn-block btn-lg btn-info" %>
        </div>
</main>

app/views/redirection/login_user_type.html.erb
<nav class="navbar navbar-inverse" role="navigation">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
        <span class="sr-only">Toggle navigation</span>
      </button>
      <a class="navbar-brand" href="/">팀플의 세계</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse-01">
      <p class="navbar-text navbar-right">
          <% flash.each do |key, value| %>
              <%= value %>
          <% end %>
      </p>
    </div><!-- /.navbar-collapse -->
</nav>
<main class="session">
    <div class="valign-wrapper">
        <div class="valign">
            -&nbsp;<h1 id="welcome" style="display:inline"></h1><br><br>
            -&nbsp;<small id="desc"></small>
            <hr>
            <% unless params.has_key?(:new) && params[:new] == 'true' then %>
                <section>
                    <a href="<%= new_user_session_path %>"><button class="btn btn-lg btn-block btn-primary btn_embossed">학생</button></a><br>
                    <a href="<%= new_owner_session_path %>"><button class="btn btn-lg btn-block btn-success btn_embossed">카페 주인</button></a>
                    <hr>
                    만약 회원이 아니시면, 회원가입 후에 서비스를 이용하실 수 있습니다.<br><br>
                    <%= button_to "회원가입", "/login", {method: :post, params:{new: true}, class:"btn btn-hg btn-block btn-info btn-embossed"} %>
                </section>
            <% else %>
                <section>
                    <a href="<%= new_user_registration_path %>"><button class="btn btn-lg btn-block btn-primary btn_embossed">학생</button></a><br>
                    <a href="<%= new_owner_registration_path %>"><button class="btn btn-lg btn-block btn-success btn_embossed">카페 주인</button></a>
                </section>
            <% end %>
            <hr>
        </div>
    </div>
</main>
<script>
      var theater = theaterJS();
        theater.on('type:start, erase:start', function () {
            theater.getCurrentActor().$element.classList.add('actor__content--typing');
        }).on('type:end, erase:end', function () {
            theater.getCurrentActor().$element.classList.remove('actor__content--typing');
        });
        
        theater
        .addActor('welcome')
        .addActor('desc')
        .addScene('welcome:환영합니다.', 600)
        .addScene('desc:회원 유형을 선택하여주세요.', 400)
        .addScene(theater.replay.bind(theater));
</script>