config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get '/intro' => 'redirection#intro'
  get '/how_to' => 'redirection#instructions'
  
  get '/create/group' => 'home#create_group'
  post '/create/group' => 'home#create_group_exec'
  get '/create/place' => 'home#create_place'
  post '/create/place' => 'home#create_place_exec'
  
  get '/find/group' => 'home#group'
  
  get '/find/place' => 'home#place'
  
  post '/find/place/like' => 'home#likes'
  
  post '/find/place/search' => 'home#place_search'
  post '/find/group/search' => 'home#group_search'
  
  get '/find/group/detail/:group_id' => 'home#group_detail'
  get '/find/place/detail/:place_id' => 'home#place_detail'
  
  get '/find/group/apply/:group_id' => 'home#group_apply'
  post '/find/place/apply/before' => 'home#place_apply_before'
  post '/find/place/apply/before/cautions' => 'home#place_apply_before_confirm'
  post '/find/place/apply' => 'home#place_apply'
  post '/find/group/apply/:place_id' => 'home#group_apply_exec'
  post '/find/place/apply/:place_id' => 'home#place_apply_exec'
  post '/find/group/destroy/:group_id' => 'home#group_destroy_exec'
  post '/find/place/destroy/:place_id' => 'home#place_destroy_exec'
  
  get '/find/group/edit/:group_id' => 'home#group_edit'
  get '/find/place/edit/:place_id' => 'home#place_edit'
  post '/find/place/edit/:place_id' => 'home#place_edit_exec'
  post '/find/group/edit/:group_id' => 'home#group_edit_exec'
  
  delete '/find/group/cancel/:group_id' => 'home#group_cancel'
  delete '/find/place/cancel/:place_id' => 'home#place_cancel'
  
  post '/find/group/member_out' => 'home#member_out'
  
  get '/mypage/reservations/:resv_id' => 'home#reservations'
  post '/mypage/reservations/cancel' => 'home#reservations_cancel'
  post '/mypage/reservations/confirm' => 'home#reservations_confirm'
  
  post '/find/place/reservation/search' => 'home#resv_search'
  
  
  get '/login' => 'redirection#login_user_type'
  post '/login' => 'redirection#login_user_type'
  
  get '/mypage'=>'home#mypage'
  
  get '/mypage/timetable' => 'home#timetable'
  get '/mypage/timetable/edit' => 'home#timetable_edit'
  post '/mypage/timetable/edit' => 'home#timetable_edit_exec'
  
  devise_for :users, controllers: { sessions: 'users/sessions' , registrations: 'users/registrations' }
  devise_for :owners, controllers: { sessions: 'users/sessions' }
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_login
  
  # REDIRECTION FOR USER CONTROL
  # def index
  #   if user_signed_in?
  #     redirect_to '/home/user_main'
  #   elsif owner_signed_in?
  #     redirect_to '/home/owner_main'
  #   else
  #     redirect_to '/home/intro'
  #   end
  # end
  
  # LIKES
  def likes
    likes = Place.find(params[:pid])
    likes.likes = likes.likes + 1
    likes.who_likes_it = "#{likes.who_likes_it}#{params[:uid]}|"
    if likes.save then
      respond_to do |format|
       format.json { 
          render json: {:likes => likes.likes}
       }
      end
    end
  end
  # END 
  
  # CREATE
  def create_group
    if owner_signed_in? then
      unauthorized
    else
      if Timetable.where("user_id = ?", current_user.id).count == 0 then
        flash[:timetable] = "시간표 등록을 하지 않으실 경우 그룹 등록이 불가합니다."
        redirect_to mypage_path
      else
      end
    end
  end
  
  def create_group_exec
    if user_signed_in? then
      insert = Group.new
      insert.school = params[:school]
      insert.name = params[:name]
      insert.content = params[:content]
      insert.member = params[:max].to_i
      insert.creator = current_user.email
      if insert.save then
        flash[:created] = "생성되었습니다."
        redirect_to mypage_path
      else
        flash[:error] = "저장 중 문제가 발생하였습니다. 다시 시도해주세요."
        redirect_to root_path
      end
      
    else
      unauthorized
    end
  end
  
  def create_place
    if user_signed_in? then
      unauthorized
    else
      if Place.where(creator: current_owner.email).count > 0 then
        flash[:already]="이미 장소를 생성한 이력이 있습니다."
        redirect_to mypage_path
      end
    end
  end
  
  def create_place_exec
    if owner_signed_in? then
      if params[:open].to_i > params[:close].to_i then
        flash[:time] = "매장 오픈/클로징 시간이 올바르지 않습니다. 생성 정보를 처음부터 다시 입력하여주시기 바랍니다."
        redirect_to create_place_path
      else
        insert = Place.new
        insert.name = params[:name]
        insert.content = params[:content]
        insert.location = params[:location]
        insert.open = params[:open]
        insert.close = params[:close]
        insert.creator = current_owner.email
        insert.likes = 0
        insert.who_likes_it = ""
        if insert.save then
          flash[:created] = "생성되었습니다."
          redirect_to mypage_path
        else
          flash[:error] = "저장 중 문제가 발생하였습니다. 다시 시도해주세요."
          redirect_to root_path
        end
      end
    else
      unauthorized
    end
  end
  
  # END
  
  # MYPAGE
  def mypage
    if user_signed_in? then
      @timetable = Timetable.where(user_id: current_user.id)
      
      if @timetable.count == 0 then
        @timetable_msg = true
      else
        @timetable = @timetable.first
        @timetable = [[@timetable.mon_time_09, @timetable.mon_time_10, @timetable.mon_time_11, @timetable.mon_time_12, @timetable.mon_time_13, @timetable.mon_time_14, @timetable.mon_time_15, @timetable.mon_time_16, @timetable.mon_time_17, @timetable.mon_time_18, @timetable.mon_time_19],
                      [@timetable.tue_time_09, @timetable.tue_time_10, @timetable.tue_time_11, @timetable.tue_time_12, @timetable.tue_time_13, @timetable.tue_time_14, @timetable.tue_time_15, @timetable.tue_time_16, @timetable.tue_time_17, @timetable.tue_time_18, @timetable.tue_time_19],
                      [@timetable.wed_time_09, @timetable.wed_time_10, @timetable.wed_time_11, @timetable.wed_time_12, @timetable.wed_time_13, @timetable.wed_time_14, @timetable.wed_time_15, @timetable.wed_time_16, @timetable.wed_time_17, @timetable.wed_time_18, @timetable.wed_time_19],
                      [@timetable.thu_time_09, @timetable.thu_time_10, @timetable.thu_time_11, @timetable.thu_time_12, @timetable.thu_time_13, @timetable.thu_time_14, @timetable.thu_time_15, @timetable.thu_time_16, @timetable.thu_time_17, @timetable.thu_time_18, @timetable.thu_time_19],
                      [@timetable.fri_time_09, @timetable.fri_time_10, @timetable.fri_time_11, @timetable.fri_time_12, @timetable.fri_time_13, @timetable.fri_time_14, @timetable.fri_time_15, @timetable.fri_time_16, @timetable.fri_time_17, @timetable.fri_time_18, @timetable.fri_time_19]
                      ]
        
        @mon = Array.new
        @tue = Array.new
        @wed = Array.new
        @thu = Array.new
        @fri = Array.new
        
        @timetable[0].each do |mon|
          @mon << timeType(mon)
        end
        
        @timetable[1].each do |tue|
          @tue << timeType(tue)
        end
        
        @timetable[2].each do |wed|
          @wed << timeType(wed)
        end
        
        @timetable[3].each do |thu|
          @thu << timeType(thu)
        end
        
        @timetable[4].each do |fri|
          @fri << timeType(fri)
        end
      end
      
      @session = current_user.email
      @affiliated = Group.where("affiliation LIKE ?", "%#{current_user.email}%")
      @myGroup = Group.where(creator: @session)
      
      @myResv = Array.new
      @myGroup.each do |g|
         r = Reservation.where("group_id =?", g.id)
         r.each do |s|
           @myResv << [s.id, Place.find(s.place_id).name]
         end
      end

    elsif owner_signed_in? then
      @session = current_owner.email
      @reservation = Reservation.where("place_id =?", )
    end
  end
  # END
  
  # GROUP
  def group
    if user_signed_in? then
      @school = current_user.school
      # @group = Group.all.paginate(:page => params[:page], :per_page => 8).order('created_at DESC')
      @group = Group.where(:school => @school).paginate(:page => params[:page], :per_page => 8).order('created_at DESC')
    else
      @group = Group.paginate(:page => params[:page], :per_page => 8).order('created_at DESC')
    end
  end
  
  def group_apply_exec
    if user_signed_in? then
      if Timetable.where("user_id = ?", current_user.id).count == 0 then
        flash[:timetable] = "시간표 등록을 하지 않으실 경우 그룹 가입이 불가합니다."
        redirect_to mypage_path
      else
         if params.has_key?(:group_id) then
          apply = Group.find(params[:group_id])
          apply.affiliation = "#{apply.affiliation}#{current_user.email}|"
          apply.member = apply.member - 1
          if apply.save then
            flash[:success] = '그룹에 가입되었습니다.'
            redirect_to  "/find/group/detail/" + params[:group_id]
          end
         else
          unauthorized
         end
      end
    
    else
      unauthorized
    end
  end
  
  def group_detail
    @group = Group.find(params[:group_id])
    if owner_signed_in? then
      @creator = false
      @signed = "not_user"
    else
      if Group.where("id = ? AND creator = ?", params[:group_id], current_user.email).count == 1 then
        @creator = true
      else
        @creator = false
        if Group.where("id = ? AND affiliation LIKE ?", params[:group_id], "%#{current_user.email}%").count == 1 then
          @signed = true
        else
          @signed = false
        end
      end
    end
    if @creator == true or @signed == true then
     memberIds = Array.new
     unless @group.affiliation == nil or @group.affiliation == "" then
       memberIds << User.where(email: @group.creator).first.id
       @group.affiliation.split('|').each do |m|
         memberIds << User.where(email: m).first.id
       end
       @canbeGatheredAt = whenTogether memberIds
     end
    end
  end

  def group_destroy_exec
    if user_signed_in? then
      if Group.find(params[:group_id]).creator == current_user.email then
        if Group.find(params[:group_id]).delete then
          flash[:success] = "그룹을 삭제하였습니다."
          redirect_to mypage_path
        end   
      else
        delete = Group.find(params[:group_id])
        delete.member = delete.member + 1
        delete.affiliation = delete.affiliation.gsub(current_user.email + '|', "")
        if delete.save then
          flash[:success] = "탈퇴하였습니다."
          redirect_to mypage_path
        end    
      end
    else
      unauthorized
    end
  end
  
  def group_edit
    if user_signed_in? then
      @group = Group.find(params[:group_id])
      if @group.affiliation == nil then
        @affiliated = 0
      else
        @affiliated = @group.affiliation.split('|').count
      end
      
      unless @group.creator == current_user.email then
        unauthorized
      end
    else
      unauthorized
    end
  end
  
  def group_edit_exec
    if user_signed_in? then
      @group = Group.find(params[:group_id])
      @group.name = params[:name]
      @group.content = params[:content]
      if @group.affiliation == nil or @group.affiliation == "" then
        @affiliated = 0
      else
        @affiliated = @group.affiliation.split('|').count
      end
      @group.member = params[:max].to_i - @affiliated.to_i
      if @group.save then
        flash[:succeess] = "수정이 완료되었습니다."
        redirect_to mypage_path
      end
    else
      unauthorized
    end
  end
  
  def group_search
    @result = Group.where(:school => current_user.school).where("name LIKE ?","%#{params[:query]}%").paginate(:page => params[:page], :per_page => 8).order('created_at DESC')
  end
  # END
  
  # PLACE
  def place
    @place = Place.all.paginate(:page => params[:page], :per_page => 8).order('created_at DESC')
  end
  
  def place_detail
    @place = Place.find(params[:place_id])
    if owner_signed_in? then
      @creator = (@place.creator == current_owner.email)
    else
      @creator = nil
    end
  end
  
  def place_apply_exec
    if user_signed_in? then
      resv = Reservation.new
      resv.place_id = params[:place_id]
      resv.group_id = params[:group_id]
      resv.confirm = 0
      resv.schedule = DateTime.parse("#{params[:selectedDate]} #{params[:resv_time]}")
      resv.duration = DateTime.parse("#{params[:selectedDate]} #{params[:duration_time]}")
      if resv.save then

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_mypage_owner.html.erb
<section>
    <!--OWNER CREATED PLACE INFORMATION AREA-->
    <h5 id="reserved">예약 미승인</h5>
        <ul>
            <li class="tagsinput">
                <% Reservation.where(place_id: Place.where(creator: current_owner.email).first).where(confirm: "0").each do |data| %>
                    <a class="tag" href="/mypage/reservations/<%= data.id %>"><%= Group.find(data.group_id).creator %></a>
                   <!-- <a class="tag" href="/find/group/detail/<%= data.group_id %>"><%= Group.find(data.group_id).creator %></a>-->
                <% end %>
            </li>
        </ul>
    <h5 id="reserved">예약 승인 완료</h5>
        <ul>
            <li class="tagsinput">
                <% Reservation.where(place_id: Place.where(creator: current_owner.email).first).where(confirm: "1").each do |data| %>
                    <a class="tag" href="/mypage/reservations/<%= data.id %>"><%= Group.find(data.group_id).creator %></a>
                   <!-- <a class="tag" href="/find/group/detail/<%= data.group_id %>"><%= Group.find(data.group_id).creator %></a>-->
                <% end %>
            </li>
        </ul>
    <a href="/find/place/edit/<%= Place.where(creator: current_owner.email).first.id %>"><button class="btn btn-lg btn-block btn-primary">등록한 장소 정보 변경</button></a>
</section>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-embossed navbar-static-top" role="navigation">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="sr-only">Toggle navigation</span>
      </button>
      <a class="navbar-brand" href="/">팀플의 세계</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav">
          <li <%= if current_page?(root_path) then 'class="active"'.html_safe end %>><a href="/">HOME</a></li>
          <% if user_signed_in? then %>
          <li <%= if current_page?(create_group_path) then 'class="active"'.html_safe end %>><a href="/create/group">그룹 생성</a></li>
          <% end %>
          <li <%= if current_page?(find_group_path) then 'class="active"'.html_safe end %>><a href="/find/group">그룹 찾기</a></li>
          <% if owner_signed_in? then %>
          <li <%= if current_page?(create_place_path) then 'class="active"'.html_safe end %>><a href="/create/place">장소 생성</a></li>
          <% end %>
          <li <%= if current_page?(find_place_path) then 'class="active"'.html_safe end %>><a href="/find/place">장소 찾기</a></li>
          <li <%= if current_page?(mypage_path) then 'class="active"'.html_safe end %>><a href="/mypage">Mypage</a></li>
      </ul>

    <% if user_signed_in? then %>
      <p class="navbar-text navbar-right">학생 계정으로 로그인됨</p>
    <% elsif owner_signed_in? then %>
      <p class="navbar-text navbar-right">카페 주인 계정으로 로그인됨</p>
    <% end %>
    <a href="<%= destroy_user_session_path %>" class="navbar-right btn btn-default navbar-btn btn-sm">로그아웃</a>
    </div><!-- /.navbar-collapse -->
  </nav>

app/views/home/group_detail.html.erb
<%= render 'home/navbar' %>
<main>
    <% flash.each do |key, value| %>
        <div class="row container">
            <div class="tip <%= key %>" align="center">
                <%= value %>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true" style="color:white;">&times;</span></button>
            </div>
        </div>
        <br>
    <% end %>
    <div class="container">
        <div class="four columns">
            <h3><%= @group.name %></h3>
            <hr>
            <span>
                <% if @creator == true then %>
                    그룹 생성자입니다.
                <% elsif @signed == "not_user" then %>
                    <b>가입 불가</b>
                <% else %>
                    <% if @signed == false then %>
                        <% if @group.member == 0 then %>
                            <b>가입 불가</b>
                        <% else %>
                            <b>가입 가능</b>
                        <% end %>
                    <% else %>
                        <b>이미 가입됨</b>
                    <% end %>
                <% end %>
            </span><br>
            <span><strong><%= @group.member %></strong>명 추가 가입 가능<%= if @group.member == 0 then '&nbsp;<b>[마감]</b>'.html_safe end %></span>
            <hr>
            <h5>생성자</h5>
            <%= @group.creator %>
            <% if @creator == true or @signed == true then %>
            <hr>
            <h5>그룹 가입자 목록</h5>
                <% if @group.affiliation == nil or @group.affiliation == "" then %>
                가입자가 없습니다.
                <% else %>
                    <% 0.upto(@group.affiliation.split('|').count-1) do |i| %>
                        <%= @group.affiliation.split('|')[i] %>
                        <% if @creator then %>
                            <%= button_to "삭제", find_group_member_out_path, {method: :post, params:{group_id: params[:group_id] , member_info: @group.affiliation.split('|')[i]}, class:"btn btn-xs btn-block btn-warning"} %>
                        <% end %>
                        <br>
                    <% end %>
                <% end %>
            <% end %>
        </div>
        <div class="eight columns">
            <p>
                <h5>그룹 소속</h5>
                <%= @group.school %>
                <h5>그룹 정보</h5>
                <%= @group.content %>
                <% if @creator==true or @signed==true then %>
                    <hr>
                    <!-- IF AFFILIATED GROUP THEN -->
                    <h5>그룹 활동에 적합한 시간을 추천합니다.</h5>
                    <% if (@group.affiliation == nil or @group.affiliation == "") then %>
                        아직 그룹에 가입자가 없어 시간 추천을 할 수 없습니다.
                    <% else %>
                        <% if @canbeGatheredAt != nil then %>
                            <div class="tagsinput">
                            <% days = ['월', '화', '수', '목', '금'] %>
                            <% i = 0 %>
                            <% j = 9 %>
                            <% @canbeGatheredAt.each do |times| %>
                                <% 0.upto(times.length-1) do |k| %>
                                    <% if times[k] == "ABLE" then %>
                                        <span class="tag"><%= days[i] %>요일 <%= j+k %>시 ~ <%= j+k+1 %>시</span>
                                    <% end %>
                                <% end %>
                                <% i = i + 1 %>
                            <% end %>
                            </div>
                            <div class="tip" align="center">
                                ※ 모임 가능 시간대는 1시간 단위로 계산되어 추천됩니다.
                                <hr>
                                ※ 20시 이후의 개인 일정은 계산되지 않았습니다.
                            </div>
                        <% else %>
                            그룹 내 가입자 간 팀프로젝트를 수행할 수 있는 적합한 시간대가 없습니다.
                        <% end %>
                    <% end %>
                    
                    <hr>
                    <h5>그룹 모임 예정 장소</h5>
                    <p>현재 예약된 장소가 없습니다.</p>
                <% else %>
                <% end %>
            </p>
            <hr>
            <% if @creator == true then %>
                <button class="btn btn-lg btn-block btn-disabled">사용자가 생성한 그룹</button><br>
                <a href="/find/group/edit/<%= params[:group_id] %>"><button class="btn btn-lg btn-block btn-embossed btn-disabled">그룹 수정</button></a><br>
                <%= button_to "그룹 삭제", "/find/group/destroy/"+params[:group_id], {data: { confirm: "그룹을 삭제합니다. 진행하시겠습니까?" }, method: :post, class:"btn btn-lg btn-block btn-primary", params:{group_id: params[:group_id]}} %>
            <% elsif @signed == "not_user" then %>
                <button class="btn btn-lg btn-block btn-disabled">카페 주인 계정은 그룹 생성/가입 등이 불가합니다.</button>
            <% else %>
                <% if @signed == false then %>
                    <% if @group.member == 0 then %>
                        <button class="btn btn-lg btn-block btn-disabled">그룹 가입 마감</button>
                    <% else %>
                        <%= button_to "그룹 가입", "/find/group/apply/"+params[:group_id], {method: :post, class:"btn btn-lg btn-block btn-primary", params:{group_id: params[:group_id]}} %>
                    <% end %>
                <% else %>
                    <button class="btn btn-lg btn-block btn-disabled">이미 가입된 그룹</button><br>
                    <%= button_to "그룹 탈퇴", "/find/group/destroy/"+params[:group_id], {data: { confirm: "그룹을 탈퇴합니다. 진행하시겠습니까?" },method: :post, class:"btn btn-lg btn-block btn-primary", params:{group_id: params[:group_id]}} %>
                <% end %>
            <% end %>
            <hr>
        </div>
    </div>
</main>

app/views/home/index.html.erb
<%= render 'home/navbar' %>
<% flash.each do |key, value| %>
  <main align="center" class="<%= key %>">
    <div class="container">
      <%= value %>
    </div>
  </main>
<% end %>
<main align="center" style="padding:0; margin:0 atuo;">
  <div id="player"></div>
  <!--<iframe width="100%" height="720" src="https://www.youtube-nocookie.com/embed/cI2QRiAIvG0?rel=0&autoplay=1&controls=0&showinfo=0" frameborder="0"></iframe>-->
</main>


<script src="//www.youtube.com/player_api"></script>

<script>
    
    // create youtube player
    var player;
    function onYouTubePlayerAPIReady() {
        player = new YT.Player('player', {
          height: '720',
          width: '100%',
          //cI2QRiAIvG0
          videoId: 'cI2QRiAIvG0',
          
          events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange
          }
        });
    }

    // autoplay video
    function onPlayerReady(event) {
        event.target.playVideo();
    }

    // when video ends
    function onPlayerStateChange(event) {        
        if(event.data === 0) {            
            location.href="/intro";
        }
    }
    
</script>

app/views/home/mypage.html.erb
<%= render 'home/navbar' %>
<main>
    <div class="container">
        <% flash.each do |key, value| %>
        <div class="row">
            <div class="tip <%= key %>" align="center">
                <%= value %>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true" style="color:white;">&times;</span></button>
            </div>
            
        </div>
        <br>
        <% end %>
        <div class="row">
            <div class="four columns">
                <h4><%= @session %>님</h4>
                <% if user_signed_in? then %>
                    <span>학생 계정</span>
                    <hr>
                    <section align="center" class="tile">
                        <!--USER TIMETABLE AREA-->
                        <h5>시간표</h5>
                        <hr>
                        <% unless @timetable_msg == true then %>
                        <div class="timetable"></div>
                        <br>
                        <a href="/mypage/timetable/edit"><button class="btn btn-lg btn-block btn-warning btn-embossed">시간표 수정</button></a>
                        <% else %>
                        <b>시간표 정보가 없습니다.<br>시간표를 생성하셔야 그룹 가입 및 팀플 시간 추천이 가능합니다.</b>
                        <hr>
                        <a href="/mypage/timetable/"><button class="btn btn-lg btn-block btn-danger btn-embossed">시간표 생성</button></a>    
                        <% end %>
                    </section>
                <% elsif owner_signed_in? then %>
                    <span>카페 주인 계정</span>
                    <hr>
                    <section class="row tile">
                    <!--OWNER INFOMATION AREA-->
                            <% if Place.where(creator: current_owner.email).count != 0 then %>
                             <div align="center">
                                <h4>예약된 건</h4>
                                <hr>
                                <h1><%= Reservation.where(place_id: Place.where(creator: current_owner.email).first.id).count %>건</h1>
                                <a data-scroll href="#reserved"><button class="btn btn-lg btn-block btn-default">자세히</button></a>
                            </div>
                    </section>
                            <% else %>
                            <div class="tip" align="center">등록된 장소가 없어 표시할 정보가 없습니다.</div>
                    </section>
                            <% end %>
                            
                <% end %>
            </div>
            <div class="eight columns">
                <% if user_signed_in? then %>
                    <%= render 'home/mypage_user' %>
                <% elsif owner_signed_in? then %>
                    <% if Place.where(creator: current_owner.email).count != 0 then %>
                    <%= render 'home/mypage_owner' %>
                    <% else %>
                    <% end %>
                <% end %>
                <hr>
                <div class="row container">
                    <div class="six columns">
                    <% if user_signed_in? then %>
                      <a href="<%= edit_user_registration_path %>"><button class="btn btn-lg btn-block btn-warning btn-embossed">회원정보 수정</button></a>
                    </div>
                    <div class="six columns">
                        <a href="<%= edit_user_registration_path + '#destroy' %>"><button class="btn btn-lg btn-block btn-danger btn-embossed">회원 탈퇴</button></a>
                    </div>
                    <% elsif owner_signed_in? then %>
                      <a href="<%= edit_owner_registration_path %>"><button class="btn btn-lg btn-block btn-warning btn-embossed">회원정보 수정</button></a>
                      </div>
                    <div class="six columns">
                        <a href="<%= edit_owner_registration_path + '#destroy' %>"><button class="btn btn-lg btn-block btn-danger btn-embossed">회원 탈퇴</button></a>
                    </div>
                    <% end %>
                </div>
                <hr>
            </div>
        </div>
    </div>
</main>

app/views/home/owner_main.html.erb
<h1>카페주인 메인페이지</h1>
<%=current_owner.email%>
<a href="/owners/sign_out">로그아웃</a>

app/views/home/place_apply_before.html.erb
<%= render 'home/navbar' %>
<main>
    <div class="container">
        <div class="tip" align="center">[유의사항] 장소 예약은 그룹 생성자만 가능합니다.</div>
        <hr>
        <h3>장소를 사용할 그룹 선택</h3>
        <hr>
        <% if @myGroup.count == 0 then %>
            예약 신청할 수 있는 그룹이 존재하지 않습니다.
            <hr>
            <%= link_to "돌아가기", "/find/place/detail/"+params[:place_id], class:"btn btn-lg btn-block btn-info" %>
        <% else %>
            <% i = 1 %>
            <% @myGroup.each do |group| %>
                <% if i % 2 == 1 then %>
                <div class="row">
                    <div class="tile six columns">
                        <h5><%= group.name %></h5>
                        <hr>
                        <% if Reservation.where(place_id: params[:place_id], group_id: group.id).count == 0 then %>
                            <%= button_to "예약 진행", "/find/place/apply", {method: :post, params:{place_id: params[:place_id], group_id: group.id}, class:"btn btn-lg btn-block btn-warning"} %>
                        <% else %>
                            <%= button_to "예약 진행", "/find/place/apply/before/cautions", {method: :post, params:{place_id: params[:place_id], group_id: group.id}, class:"btn btn-lg btn-block btn-warning"} %>
                        <% end %>
                    </div>
                <% else %>
                    <div class="tile six columns">
                        <h5><%= group.name %></h5>
                        <hr>
                        <% if Reservation.where(place_id: params[:place_id], group_id: group.id).count == 0 then %>
                            <%= button_to "예약 진행", "/find/place/apply", {method: :post, params:{place_id: params[:place_id], group_id: group.id}, class:"btn btn-lg btn-block btn-warning"} %>
                        <% else %>
                            <%= button_to "예약 진행", "/find/place/apply/before/cautions", {method: :post, params:{place_id: params[:place_id], group_id: group.id}, class:"btn btn-lg btn-block btn-warning"} %>
                        <% end %>
                    </div>
                </div>
                <% end %>
                <% i = i +1 %>
            <% end %>
            <% if @myGroup.count % 2 == 1 then %>
                </div>
            <% end %>
        <% end %>
        <hr>
    </div>
</main>

app/views/home/place_cancel.html.erb
<%= render 'home/navbar' %>
<main>
    <h1>장소 예약 취소</h1>
    <hr>
    
</main>